glove_path: '../GeNeVA_datasets/data/CRIM/glove_crim.txt'

# codraw: '../GeNeVA_datasets/data/CoDraw/codraw_train.h5'
# codraw_background: '../GeNeVA_datasets/data/CoDraw/background.png'
# codraw_objects: '../GeNeVA_datasets/data/CoDraw/objects.txt'
# codraw_test: '../GeNeVA_datasets/data/CoDraw/codraw_test.h5'
# codraw_val: '../GeNeVA_datasets/data/CoDraw/codraw_val.h5'

# iclevr: '../GeNeVA_datasets/data/iCLEVR/clevr_train.h5'
# iclevr_background: '../GeNeVA_datasets/data/iCLEVR/background.png'
# iclevr_objects: '../GeNeVA_datasets/data/iCLEVR/objects.txt'
# iclevr_test: '../GeNeVA_datasets/data/iCLEVR/clevr_test.h5'
# iclevr_val: '../GeNeVA_datasets/data/iCLEVR/clevr_val.h5'


# codraw_inception_objects: 'models/codraw_inception_best_checkpoint.pth'

# iclevr_inception_objects: 'models/iclevr_inception_best_checkpoint.pth'


crim: '../GeNeVA_datasets/data/CRIM/clevr_train.h5'
crim_objects: '../GeNeVA_datasets/data/CRIM/objects.txt'
crim_test: '../GeNeVA_datasets/data/CRIM/clevr_test.h5'
crim_val: '../GeNeVA_datasets/data/CRIM/clevr_val.h5'
